// bakes subset Inter fonts into base64 -> ships inside Vercel Function bundle
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = new URL('../lib/fonts/', import.meta.url).pathname;
const weights = [400, 600];

const parts = weights.map((w) => {
  const base64 = readFileSync(join(DIR, `inter-${w}.ttf`)).toString('base64');
  return `export const INTER_${w} =\n  '${base64}';`;
});

writeFileSync(
  join(DIR, 'inter.ts'),
  `// generated by scripts/make-fonts.mjs, do not edit, Inter = SIL OFL 1.1\n${parts.join('\n\n')}\n`,
);

console.log(`make-fonts: wrote inter.ts (${weights.join(', ')})`);
